# Generated by Django 4.2.28 on 2026-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('companyLogo', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('locationType', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='Remote', max_length=50)),
                ('jobType', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], default='Full-time', max_length=50)),
                ('salary', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('aboutCompany', models.TextField()),
                ('postedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
