# Generated by Django 4.2.28 on 2026-02-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_job_status_job_submittedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SubadminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, default='', max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('profileUrl', models.URLField(blank=True, default='', help_text='LinkedIn, GitHub, portfolio, etc.', max_length=500)),
                ('avatarUrl', models.URLField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
