# Generated by Django 4.2.28 on 2026-02-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_job_company_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='aboutCompany',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='companyLogo',
        ),
        migrations.AlterField(
            model_name='job',
            name='company_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company'),
        ),
    ]
