# Generated by Django 4.2.28 on 2026-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_aboutcompany_remove_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
