# Generated by Django 4.2.28 on 2026-03-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
