# Generated by Django 4.2.28 on 2026-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('INR', 'INR (₹)')], default='INR', max_length=10),
        ),
    ]
